// .vitepress/theme/components/posts/PostBanner.vue
<template>
  <Banner v-if="currentPost"
          :title="currentPost.title"
          :subtitle="`发布于${
        Intl.DateTimeFormat('zh-CN', {
          year: 'numeric',
          month: '2-digit',
          day: '2-digit',
        }).format(new Date(currentPost.create))
      }
      | 约${ currentPost.wordCount }字 | ${ currentPost.collection }`"
  ></Banner>

</template>
<script setup lang="ts">
import { computed } from 'vue'
import { useData, useRoute } from 'vitepress'
import { resolveCurrentPost } from '../../utils/currentPost'
import Banner from '../shared/Banner.vue'

const { page } = useData()
const route = useRoute()
const base = useData().site.value.base

const currentPost = computed(() => {
  return resolveCurrentPost({
    relativePath: page.value.relativePath,
    routePath: route.path,
    base,
  })
})

</script>

// components/posts/PostBanner.tsx
import { Banner } from '@/components/shared/Banner'
import type { Post } from '@/lib/types'

type PostBannerProps = {
  post?: Post
}

function formatDate(timestamp: number) {
  return new Intl.DateTimeFormat('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(new Date(timestamp))
}

export function PostBanner({ post }: PostBannerProps) {
  if (!post) {
    return null
  }

  return (
    <Banner
      title={post.title}
      subtitle={`发布于${formatDate(post.create)}
      | 约${post.wordCount}字 | ${post.collection ?? ''}`}
    />
  )
}
